# Generated by Django 3.2 on 2022-11-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categroy',
            new_name='category',
        ),
    ]
